version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: npm
    versions:
    - 6.14.11
    - 6.14.12
  - dependency-name: netlify-cms-app
    versions:
    - 2.14.10
    - 2.14.17
    - 2.14.23
    - 2.14.24
    - 2.14.32
  - dependency-name: "@types/react"
    versions:
    - 17.0.0
    - 17.0.2
  - dependency-name: gatsby-plugin-react-helmet
    versions:
    - 3.8.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: handlebars
    versions:
    - 4.7.6
  - dependency-name: jquery
    versions:
    - 3.5.1
