// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:d513929e-5ea7-4c82-8aca-6fba457026c2",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_Oji0cg9wB",
    "aws_user_pools_web_client_id": "4so88lp3l5beocklhsbd64jlqn",
    "oauth": {
        "domain": "peaty-pwa1e26d4b1-1e26d4b1-dev.auth.eu-west-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://peaty-rota.netlify.com/",
        "redirectSignOut": "https://peaty-rota.netlify.com/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "https://4thxwa56ybcunk5b6uflnxfetu.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_content_delivery_bucket": "peaty-rota-dev-dev",
    "aws_content_delivery_bucket_region": "eu-west-1",
    "aws_content_delivery_url": "http://peaty-rota-dev-dev.s3-website-eu-west-1.amazonaws.com"
};


export default awsmobile;
